### ISSUE TITLE
Example Broken on extra large screens

### ISSUE THREAD

**Issue by paulcpederson** [esripdx/viewport-grid#23]
Somehow the columns are filling up to 25 before they break:

![screen shot 2015-07-21 at 11 07 23 am](https://cloud.githubusercontent.com/assets/1031758/8808654/c8ae645c-2f98-11e5-88f8-c89fd5b8dc48.png)

Pretty weird

**Comment by nikolaswise** [comment]
Not a bug! 1 + 23 + 3 < 36, but 1 + 23 + 2 + 22 > 36. Wraps as needed.
