### ISSUE TITLE
Un-nested column-4 example on Examples page misaligned

### ISSUE THREAD

**Issue by jkymarsh** [esripdx/viewport-grid#30]
Under the "Nested Columns" section on the Examples page, the furthest-right, bottom-most grid column-4 is slightly offset in its container on desktop - appears to be an issue with its padding, and it also has two classes `column-first tablet-first-column` that may not be working as intended.

<img width="1174" alt="screen shot 2016-01-22 at 11 30 35 pm" src="https://cloud.githubusercontent.com/assets/794433/12529061/91e42286-c160-11e5-89a2-cd9c437c45c6.png">

**Comment by paulcpederson** [comment]
@jkymarsh the class was `column-first` instead of `first-column`. Thanks for reporting! https://github.com/esripdx/viewport-grid/pull/31 should fix it!

**Comment by jkymarsh** [comment]
@paulcpederson Not sure if the site needs to be recompiled or whatnot - example isn't fixed on my end.

**Comment by paulcpederson** [comment]
yeah, hadn't deployed yet. should be fixed now though. Reopen if not!
